customers/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'sikker.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^login/', views.user_login_signup, name='login'),
    url(r'^logout/', views.user_logout, name='logout'),
    url(r'^myaccount/', views.user_profile, name='myaccount'),
    url(r'^basket', views.basket, name='basket')
]

sikker/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from . import views
from products.urls import details as details
from products.urls import list as list
from customers import urls as customers
admin.site.site_header = 'Sikker'
urlpatterns = [
    # Examples:
    # url(r'^$', 'sikker.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.home_page, name='home'),
    url(r'^product/', include(details, namespace='product')),
    url(r'^category/', include(list, namespace='category')),
    url(r'^account/', include(customers, namespace='account')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

customers/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import HStoreField

class CartOrder(models.Model):
    customer = models.ForeignKey(User)
    skus = HStoreField(db_index=False)
    address1 = models.CharField(max_length=255, blank=False, default=None)
    address2 = models.CharField(max_length=255, null=True)
    city = models.CharField(max_length=255)
    phone = models.CharField(max_length=25)

customers/forms.py
from django import forms
import django.contrib.auth
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from customers.models import CartOrder
from django.utils.translation import ugettext as _

class LoginForm(forms.Form):
    username = forms.CharField(label=_('Username'), max_length=255, required=True)
    password = forms.CharField(label=_('Password'), widget=forms.PasswordInput(), required=True)

    def is_valid(self, request):
        valid = super(LoginForm, self).is_valid()

        if valid:

            user = authenticate(username=self.cleaned_data['username'], password=self.cleaned_data['password'])

            if user is not None and user.is_active:
                login(request, user)
                return True

            else:
                self.errors['username'] = ['Password is invalid', ]
                return False

        else:
            return False

class SignupForm(forms.ModelForm):

    confirm_password = forms.CharField(label=_('Confirm password'),widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }

    def is_valid(self, request):
        valid = super(SignupForm, self).is_valid()

        if valid and self.cleaned_data['confirm_password'] != self.cleaned_data['password']:
            self.errors['confirm_password'] = ['Both passwords don\'t match', ]
            valid = False

        if valid:
            user = self.save()
            user.set_password(self.cleaned_data['password'])
            user.save()

            user = authenticate(username=self.cleaned_data['username'], password=self.cleaned_data['password'])

            if user is not None and user.is_active:
                login(request, user)
                return True

            else:
                self.errors['username'] = ['Password is invalid', ]
                return False

        else:
            return False


class MyAccountForm(forms.ModelForm):

    password = forms.CharField(required=False, widget=forms.PasswordInput)
    confirm_password = forms.CharField(label=_('Confirm password'), required=False,widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def is_valid(self):
        valid = super(MyAccountForm, self).is_valid()

        if valid and self.cleaned_data['confirm_password'] != self.cleaned_data['password']:
            self.errors['confirm_password'] = ['Both passwords don\'t match', ]
            valid = False

        return valid

    def save(self):
        user = super(MyAccountForm, self).save()
        password = self.cleaned_data['password']

        if password:
            user.set_password(password)

        user.save()
        return user

class CheckoutForm(forms.ModelForm):

    class Meta:
        model = CartOrder
        fields = ['address1', 'address2', 'city', 'phone']

    def save(self, user, skus):
        if user and skus:
            for key in skus.keys():
                skus[key] = str(skus[key])

            form = super(CheckoutForm, self).save(commit=False)
            form.customer = user
            form.skus = skus
            form.save()

customers/views.py
from django.shortcuts import redirect, render
from .forms import LoginForm, SignupForm, MyAccountForm

import sys
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import re

def user_signup(request):
    if request.method == 'POST':
        signup_form = SignupForm(request.POST)

        if signup_form.is_valid(request):
            return redirect('account:myaccount')

    form = LoginForm()

    context = {'form': form, 'signup_form': signup_form}
    return render(request, 'customers/login.html', context)

def user_login(request):

    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid(request):
            return redirect('account:myaccount')

    signup_form = SignupForm()

    context = {'form': form, 'signup_form': signup_form}
    return render(request, 'customers/login.html', context)

def user_login_signup(request):

    if 'login' in request.POST:
        return user_login(request)
    elif 'signup' in request.POST:
        return user_signup(request)
    else:
        form = LoginForm()
        signup_form = SignupForm()

    context = {'form': form, 'signup_form': signup_form}
    return render(request, 'customers/login.html', context)

@login_required
def user_profile(request):
    myaccount_form = MyAccountForm(data=request.POST or None, instance=request.user)

    if myaccount_form.is_valid():
        myaccount_form.save()

    context = { 'myaccount_form': myaccount_form }
    return render(request, 'customers/myaccount.html', context)

@login_required
def user_logout(request):
    logout(request)
    return redirect('home')

def basket(request):
    sku = request.POST.get('sku', request.GET.get('sku', False))
    qnt = request.POST.get('quantity', request.GET.get('quantity', False))

    if sku and qnt:
        basket = request.session.get('basket', default={})

        if re.match('^[+\-]?\d+$', qnt):
            qnt = int(qnt)
            if sku in basket and qnt != 0:
                basket[sku] = basket[sku] + qnt
            else:
                basket[sku] = qnt

        request.session['basket'] = basket
        return redirect('account:basket')

    return render(request, 'customers/basket.html')

customers/templates/customers/basket.html
{% extends "base/home.html" %}
{% load lib %}
{% load i18n %}
{% load staticfiles %}

{% block title %}
{% trans 'My Bag' %}
{% endblock title %}

{% block content %}
<h2>{% trans 'My Bag' %}</h2>
{% if basket.count > 0 %}
  <ul class="basket__product-list list-group">
      {% for bitem in basket.skus.values %}
      <li class="list-group-item">
        <div class="row">
          {{ bitem.sku.product | smprimage:'hidden-xs img-responsive col-sm-3 col-md-2' | safe }}
          <div class="col-xs-8 col-sm-7 col-md-8">
            <span class="product__quantity">{{bitem.quantity}}x </span>
            {{bitem.sku.product.title}}
          </div>
          <div class="col-xs-4 col-sm-2 text-right">
            {{bitem.price}} €
          </div>
          {% if bitem.sku.attributes.keys %}
          <div class="col-xs-9 col-md-10">
            <small class="product__sku-attributes">
              {{ bitem.sku.attributes | filter_dict:"color,size" | join:", " }}
              <span class="product__sku">(Sku: {{bitem.sku.sku}})</span>
            </small>
          </div>
          {% endif %}
          <div class="col-xs-9">
            <a href="{% url 'account:basket'  %}?sku={{bitem.sku.sku}}&quantity=0" class="product__delete sku_{{bitem.sku.sku}}">{% trans 'delete' %}</a>
          </div>
        </div>
      </li>
      {% endfor %}
      <li class="list-group-item">
        <div class="row">
          <div class="col-sm-push-3 col-md-push-2 col-xs-8 col-sm-7 col-md-8">
            {% trans 'Total' %}:
          </div>
          <div class="col-sm-push-3 col-md-push-2 col-xs-4 col-sm-2 text-right">
            {{basket.price}} €
          </div>
        </div>
    </li>
  </ul>
  <a href="#comprar" class="btn btn-primary col-xs-12 col-sm-auto pull-right">Comprar</a>
{% else %}
  <div class="basket__empty-list">
    {% trans "There're no products in the bag" %}
  </div>
{% endif %}
{% endblock content %}

customers/templates/customers/login.html
{% extends "base/home.html" %}
{% load lib %}
{% load i18n %}

{% block title %}
{% trans 'Login' %}
{% endblock title %}

{% block content %}
<div class="row">
  <div class="login__form col-xs-12 col-sm-6">
    <h2>{% trans 'Login' %}</h2>
    <form role="form" action="{% url 'account:login' %}" method="POST">
      {% csrf_token %}
      {{ form.non_field_errors }}
      {% for field in form %}
        <div class="form-group {% if field.errors %}has-error{% endif %}">
          {{ field | label_with_classes:"control-label" }}
          {{ field | field_with_classes:"form-control" }}
          {% for error in field.errors %}
            <span class="help-block text-right">{{error}}</span>
          {% endfor %}
        </div>
      {% endfor %}
      <p><input class="btn btn-primary col-xs-12 col-sm-auto" type="submit" value="{% trans 'Login' %}" name="login" id="login"></p>
    </form>

  </div>
  <div class="signup__form col-xs-12 col-sm-6">
    <h2>{% trans 'Sign Up' %}</h2>
    <form role="form" action="{% url 'account:login' %}" method="POST">
      {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in signup_form %}
          <div class="form-group {% if field.errors %}has-error{% endif %}">
            {{ field | label_with_classes:"control-label" }}
            {{ field | field_with_classes:"form-control" }}
            {% for error in field.errors %}
              <span class="help-block text-right">{{error}}</span>
            {% endfor %}
          </div>
        {% endfor %}
        <p><input class="btn btn-primary col-xs-12 col-sm-auto" type="submit" value="{% trans 'SignUp' %}" name="signup" id="signup"></p>
    </form>
  </div>
</div>
{% endblock content %}

customers/templates/customers/myaccount.html
{% extends "base/home.html" %}
{% load lib %}

{% block title %}
My Account
{% endblock title %}

{% block content %}
  <div class="myaccount__form row">
    <div class="col-xs-12">
      <h2>My Details</h2>
    </div>
    <div class="col-xs-12 col-sm-6">
      <form role="form" action="{% url 'account:myaccount' %}" method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in myaccount_form %}
        <div class="form-group {% if field.errors %}has-error{% endif %}">
          {{ field | label_with_classes:"control-label" }}
          {{ field | field_with_classes:"form-control" }}
          {% for error in field.errors %}
          <span class="help-block text-right">{{error}}</span>
          {% endfor %}
        </div>
        {% endfor %}
        <p><input class="btn btn-primary col-xs-12 col-sm-auto pull-sm-right" type="submit" value="Save" name="update" id="update"></p>
      </form>
    </div>

  </div>
{% endblock content %}