customers/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'sikker.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^login/', views.user_login_signup, name='login'),
    url(r'^logout/', views.user_logout, name='logout'),
    url(r'^myaccount/', views.user_profile, name='myaccount'),
    url(r'^basket', views.basket, name='basket')
]

sikker/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from . import views
from products.urls import details as details
from products.urls import list as list
from customers import urls as customers
admin.site.site_header = 'Sikker'
urlpatterns = [
    # Examples:
    # url(r'^$', 'sikker.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.home_page, name='home'),
    url(r'^product/', include(details, namespace='product')),
    url(r'^category/', include(list, namespace='category')),
    url(r'^account/', include(customers, namespace='account')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/views.py
from django.shortcuts import render
from .models import Product, Category
from django.http import Http404
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

# from django.contrib.auth.decorators import login_required
# from django.utils.decorators import method_decorator
#
# def dispatch(self, *args, **kwargs):
    # return super(DetailView, self).dispatch(*args, **kwargs)

class Details(DetailView):
    model = Product
    template_name = 'products/details.html'

    def get_context_data(self, **kwargs):
        context = super(Details, self).get_context_data(**kwargs)
        context['skus'] = context['product'].sku_set.all()
        return context

# def product_details(request, product_id):
    # try:
        # product = Product.objects.language().get(pid=product_id)
    # except Product.DoesNotExist:
        # raise Http404
    # return render(request, 'products/details.html', { 'product': product })

class List(DetailView):
    model = Category
    template_name = 'products/list.html'
    context_object_name = 'list'

    # try:
        # category = Category.objects.language().get(catid=category_id)
    # except Category.DoesNotExist:
        # raise Http404
    # return render(request, 'products/list.html', { 'list': category })

templates/base/_includes/footer.html
{% load i18n %}
<footer>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-5 list-unstyled">
        <h4 data-toggle="collapse" data-target="#customer_care">{% trans 'CUSTOMER CARE' %} <i class="hidden-sm hidden-md hidden-lg caret"></i></h4>
        <ul id="customer_care" class="list-unstyled collapse">
          <li><a href="#">{% trans 'SIZE GUIDE' %}</a></li>
          <li><a href="#">{% trans 'CONTACT US' %}</a></li>
          <li><a href="#">{% trans 'DELIVERY & RETURNS' %}</a></li>
          <li><a href="#">{% trans 'FAQ' %}</a></li>
          <li><a href="#">{% trans 'TERMS &amp; CONDITIONS' %}</a></li>
          <li><a href="#">{% trans 'GIFT CARD' %}</a></li>
        </ul>
      </div>
      <div class="col-xs-12 col-sm-5">
        <h4 data-toggle="collapse" data-target="#more_about_us">{% trans 'MORE ABOUT US' %} <i class="hidden-sm hidden-md hidden-lg caret"></i></h4>
        <ul id="more_about_us" class="list-unstyled collapse">
          <li><a href="#">{% trans 'ABOUT US' %}</a></li>
          <li><a href="#">{% trans 'PRIVACY POLICY' %}</a></li>
          <li><a href="#">{% trans 'COOKIES' %}</a></li>
          <li><a href="#">{% trans 'ACCESSIBILITY' %}</a></li>
          <li><a href="#">{% trans 'SITEMAP' %}</a></li>
          <li><a href="#">{% trans 'CAREERS' %}</a></li>
        </ul>
      </div>
      <div class="col-xs-12 col-sm-2 social-media__group">
        <h4>{% trans 'Follow Us' %}</h4>
        <a href="#" class="social-media__icon"><i class="fa fa-facebook-official"></i></a>
        <a href="#" class="social-media__icon"><i class="fa fa-twitter-square"></i></a>
        <a href="#" class="social-media__icon"><i class="fa fa-pinterest-square"></i></a>
        <a href="#" class="social-media__icon"><i class="fa fa-instagram"></i></a>
      </div>
    </div>
  </div>
</footer>

templates/base/_includes/header.html
{% load i18n %}

<div class="header__links">
  <div class="container">
    <ul class="row list-inline">
      {% if user.is_authenticated %}
      <li class="header__login dropdown">
        <a class="dropdown-toggle" href="{% url 'account:myaccount' %}">{% trans 'My Account' %} <span class="hidden-xs caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'account:myaccount' %}">{% trans 'My Details' %}</a></li>
          <li><a class="account__logout-button" href="{% url 'account:logout' %}">{% trans 'Logout' %}</a></li>
        </ul>
      </li>
      {% else %}
      <li class="header__login ">
        <a href="/account/login">{% trans 'Login' %}</a>
      </li>
      {% endif %}

      <li class="header__minibasket dropdown">
        {% include "base/_includes/minibasket.html" %}
      </li>
      <li class="language__form">
        {% include "base/_includes/language.html" %}
      </li>
    </ul>
  </div>
</div>

templates/base/_includes/home_content.html
{% load i18n %}
{% load staticfiles %}

<h3 class="text-right">{% trans 'For those romantics who love to daydream' %}</h3>
<ul class="list-unstyled row">
  {% for product in hero_products %}
  <li class="product col-xs-6 col-sm-3">
    <a class="thumbnail" href="{% url 'product:details' product.pid %}">
      <div class="product__image-wrap">
      {% with 'images/thumbs/'|add:product.attributes.image|add:'_1_1_1.jpg' as image_static %}
        <img class="img-responsive" src="{% static image_static %}" alt=""/>
      {% endwith %}
      </div>
    </a>
  </li>
  {% endfor %}
</ul>

<h3>{% trans 'For the party goers' %}</h3>
<ul class="list-unstyled row">
  {% for product in hero_products_2 %}
  <li class="product col-xs-6 col-sm-3">
    <a class="thumbnail" href="{% url 'product:details' product.pid %}">
      <div class="product__image-wrap">
        {% with 'images/thumbs/'|add:product.attributes.image|add:'_1_1_1.jpg' as image_static %}
          <img class="img-responsive" src="{% static image_static %}" alt=""/>
        {% endwith %}
      </div>
    </a>
  </li>
  {% endfor %}
</ul>

templates/base/_includes/language.html
{% load i18n %}
<form role="form" action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}" />
    <select class="submit-on-change" name="language">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
              {% trans language.name_local %}
            </option>
        {% endfor %}
    </select>
    <input class="sr-only" type="submit" value="Go" />
</form>

templates/base/_includes/menu.html
<div class="navbar navbar-default row">
  <button type="button" class="navbar-toggle collapsed navbar-left" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
    {% for category in CATEGORY_LIST %}
    <li class="dropdown main-menu__dropdown-toggle"><a data-toggle="dropdown" data-taget="#category_{{category.catid}}" class="dropdown-toggle">{{ category.title }}
        <i class="hidden-xs caret"></i>
      </a>
      {% if category.children_categories.count %}
        <ul class="dropdown-menu" id="category_{{category.catid}}">
          {% for subcat in category.children_categories.all %}
          <li><a href="{% url 'category:list' subcat.catid %}">{{ subcat.title }}</a>
          {% endfor %}
        </ul>
      {% endif %}
      </li>
    {% endfor %}
    </ul>
  </div>
</div>

templates/base/_includes/minibasket.html
{% load i18n %}
{% load lib %}
{% load staticfiles %}

<a class="header__minibasket__link" href="{% url 'account:basket' %}">
  {% blocktrans count counter=basket.count %}
  My Bag ({{counter}} Item)
  {% plural %}
  My Bag ({{counter}} Items)
  {% endblocktrans %}
  {% if basket.count %} <span class="hidden-xs caret"></span>{% endif %}
</a>

{% if basket.count %}
<ul class="minibasket dropdown-menu row">
  {% for item in basket.skus.values %}
  {% with item.sku.product as product %}
  <li class="col-xs-12">
    <a class="row nopadding" href="{% url 'product:details' product.pid %}">
      {{ product | smprimage:'img-responsive col-xs-3' | safe }}
      <span class="col-xs-6">{{item.quantity}}x {{product.title}}</span>
      <span class="col-xs-3 text-right">{{ item.price }} €</span>
      {% if item.sku.attributes.keys %}
      <small class="col-xs-9 sku_attributes">
        {{ item.sku.attributes | filter_dict:"color,size" | join:", " }}
      </small>
      {% endif %}
    </a>
  </li>
  {% endwith %}
  {% endfor %}
  <li class="minibasket-total col-xs-12">
    <div class="row">
      <h5 class="col-xs-6 col-xs-push-3">Total:</h5> <h5 class="col-xs-push-3 col-xs-3 text-right">{{basket.price}} €</h5>
    </div>
  </li>
  <li class="col-xs-12">
    <div class="row">
      <div class="col-xs-9 col-xs-push-3">
        <button href="#comprar" class="btn btn-primary col-xs-12 pull-right">Comprar</button>
      </div>
    </div>
  </li>
</ul>
{% endif %}