customers/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'sikker.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^login/', views.user_login_signup, name='login'),
    url(r'^logout/', views.user_logout, name='logout'),
    url(r'^myaccount/', views.user_profile, name='myaccount'),
    url(r'^basket', views.basket, name='basket')
]

sikker/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from . import views
from products.urls import details as details
from products.urls import list as list
from customers import urls as customers
admin.site.site_header = 'Sikker'
urlpatterns = [
    # Examples:
    # url(r'^$', 'sikker.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.home_page, name='home'),
    url(r'^product/', include(details, namespace='product')),
    url(r'^category/', include(list, namespace='category')),
    url(r'^account/', include(customers, namespace='account')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/models.py
from django.db import models
from hvad.models import TranslatableModel, TranslatedFields
from django.contrib.postgres.fields import HStoreField

class Category(TranslatableModel):
    class Meta:
        verbose_name_plural='Categories'

    catid = models.CharField(max_length=50, primary_key=True)
    parent_categories = models.ManyToManyField('self', related_name='children_categories', symmetrical=False)

    translations = TranslatedFields(
        title=models.CharField(max_length=255, default=''),
    )

    def __str__(self):
        return "[cat] %s: %s" % (self.catid, self.title)

   # TODO: Parent Category Implementation

class Product(TranslatableModel):
    pid = models.CharField(max_length=50, primary_key=True)
    category = models.ManyToManyField(Category)
    attributes = HStoreField(db_index=True, null=True, blank=True)

    translations = TranslatedFields(
        title=models.CharField(max_length=255, default=''),
        description=models.TextField(default='')
    )

    def __str__(self):
        return "[pro] %s: %s" % (self.pid, self.title)

class Sku(TranslatableModel):
    sku = models.CharField(max_length=50, primary_key=True)
    price = models.DecimalField(max_digits=20, decimal_places=2, default=0.0)
    stock = models.IntegerField(default=0)
    product = models.ForeignKey(Product)
    attributes = HStoreField(db_index=True, null=True, blank=True)

    translations = TranslatedFields(
        description=models.TextField(default='')
    )

    def __str__(self):
        return "[sku] %s" % (self.sku)

products/views.py
from django.shortcuts import render
from .models import Product, Category
from django.http import Http404
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

# from django.contrib.auth.decorators import login_required
# from django.utils.decorators import method_decorator
#
# def dispatch(self, *args, **kwargs):
    # return super(DetailView, self).dispatch(*args, **kwargs)

class Details(DetailView):
    model = Product
    template_name = 'products/details.html'

    def get_context_data(self, **kwargs):
        context = super(Details, self).get_context_data(**kwargs)
        context['skus'] = context['product'].sku_set.all()
        return context

# def product_details(request, product_id):
    # try:
        # product = Product.objects.language().get(pid=product_id)
    # except Product.DoesNotExist:
        # raise Http404
    # return render(request, 'products/details.html', { 'product': product })

class List(DetailView):
    model = Category
    template_name = 'products/list.html'
    context_object_name = 'list'

    # try:
        # category = Category.objects.language().get(catid=category_id)
    # except Category.DoesNotExist:
        # raise Http404
    # return render(request, 'products/list.html', { 'list': category })

products/templates/products/details.html
{% extends "base/home.html" %}

{% load i18n %}
{% load staticfiles %}
{% load lib %}

{% block title %}{{ product.title }}{% endblock title %}

{% block content %}
{% load lib %}
<div class="col-xs-12 col-sm-5 pull-right">
  <h2 class="product__title">{{ product.title }}</h2>
  <p class="product__description">{{ product.description }}</p>
</div>
<div class="col-xs-12 col-sm-7 pull-left form-group">
  {{ product | lgprimage:'img-responsive' | safe }}
</div>
<div class="product__add-basket col-xs-12 col-sm-5 pull-right">
  <form role="form" action="{% url 'account:basket' %}" method="post" accept-charset="utf-8">
    {% csrf_token %}

    <div class="form-group">
      <select class="form-control" name="sku">
        {% for sku in skus %}
        <option type="text" value="{{sku.sku}}">{{ sku.attributes | filter_dict:"color,size" | join:" / " | default:sku.sku }} - {{sku.price}}€</option>
        {% comment %}
          {{ sku.attributes | filter_dict:["color"] | join:" / " | default:sku.description | default:sku.sku }} - {{sku.price}}€
        {% endcomment %}
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <label for="quantity">{% trans 'Quantity' %}:</label>
      <select name="quantity" class="form-control">
        {% for qnt in quantities %}
          <option type="text" value="{{qnt}}">{{qnt}}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <input type="submit" name="submit" value="{% trans 'Add to Cart' %}" class="btn btn-primary btn-large product__add-to-cart"></p>
    </div>
  </form>
</div>

{% endblock content %}

products/templates/products/list.html
{% extends "base/home.html" %}

{% load lib %}
{% load staticfiles %}

{% block title %}
{{ list.title }}
{% endblock title %}

{% block content %}
  <h2>{{list.title}}</h2>
  <ul class="list-unstyled">
  {% for product in list.product_set.all %}
    <li class="product col-xs-6 col-sm-4 col-md-3 col-lg-2">
      <a class="thumbnail" href="{% url 'product:details' product.pid %}">
        <div class="product__image-wrap">
          {{ product | smprimage:'img-responsive' | safe }}
        </div>
        <div class="text-center product-list__product-title">{{ product.title }}</div>
      </a>
    </li>
  {% endfor %}
  </ul>
{% endblock content %}